<?php

use App\Models\Task;

?>

<div class="d-flex justify-content-between my-3">
    <div>
        <h1 class="my-0">Tasks</h1>
    </div>
    <div>
        <a class="btn btn-primary" href="/create-task">create new</a>
    </div>
</div>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>name <a class="h5 pr-2" href='?<?= $pageQuery ?>sort=name+desc'>&#9660;</a><a class="h5 pr-2" href='?<?= $pageQuery ?>sort=name+asc'>&#9650;</a></th>
            <th>email <a class="h5 pr-2" href='?<?= $pageQuery ?>sort=email+desc'>&#9660;</a><a class="h5 pr-2" href='?<?= $pageQuery ?>sort=email+asc'>&#9650;</a></th>
            <th>description</th>
            <th>status <a class="h5 pr-2" href='?<?= $pageQuery ?>sort=status+desc'>&#9660;</a><a class="h5 pr-2" href='?<?= $pageQuery ?>sort=status+asc'>&#9650;</a></th>
            <th>edited by admin</th>
        </tr>
    </thead>
    <tbody>
        <?php if (!empty($tasks)) : ?>
            <?php foreach($tasks as $task) : ?>
            <tr>
                <td><a href="/update-task?id=<?= $task['id'] ?>"><?= htmlspecialchars($task['name']) ?></a></td>
                <td><?= htmlspecialchars($task['email']) ?></td>
                <td><?= htmlspecialchars($task['description']) ?></td>
                <td><?= Task::getStatusList()[$task['status']] ?? 'undefined' ?></td>
                <td><?= $task['edited'] ? 'yes' : 'no' ?></td>
            </tr>
            <?php endforeach; ?>
            <?php else : ?>
                <tr><td colspan="5">No task so far</td></tr>
        <?php endif ; ?>
    </tbody>
</table>
<?php if(isset($totalPages)): ?>
    <ul class="pagination">
        <?php for ($i = 1; $i <= $totalPages; $i += 1): ?>
        <li class="page-item"><a class="page-link <?= $activePage === $i ? 'bg-light' : ''?>" href="/?page=<?= $i, $sortQuery ?>"><?= $i ?></a></li>
        <?php endfor; ?>
    </ul>
<?php endif; ?>