<div class="d-flex justify-content-between my-3">
    <div>
        <h1 class="my-0">Enter your email and password</h1>
    </div>
</div>
<div class="row">
    <div class="col-12 col-lg-5">
        <form method="POST">
            <div class="form-group">
                <input type="text" name="user[login]" class="form-control" placeholder="Login" required>
            </div>
            <div class="form-group">
                <input type="password" name="user[password]" class="form-control" placeholder="Password" required>
            </div>
            <button type="submit" class="btn btn-primary my-3">Submit</button>
        </form>
    </div>
</div>