<?php

use App\Models\Task;

?>
<!DOCTYPE html>
<html lang="ru-RU">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task Manager</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/dashboard.css" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Task Manager</a>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <?php if (\Core\App::$app['user']->isAdmin()): ?>
                <form method="post" class="m-0" action="/logout">
                    <button type="submit" class="btn btn-primary">
                    Log Out
                    </button>
                </form>
                <?php else: ?>
                    <a class="btn btn-primary" href="/login" data-method='post'>Log In</a>
                <?php endif; ?>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                </div>
            </nav>
        </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

    <?php if (isset($_SESSION['flash'])) : ?>
        <div class="alert alert-<?= $_SESSION['flash']['class'] ?>" role="alert">
            <strong><?= $_SESSION['flash']['message'] ?></strong>
            <?php unset( $_SESSION['flash'] );?>
        </div>
    <?php endif; ?>

            <div class="d-flex justify-content-between my-3">
                <div>
                    <h1 class="my-0">Tasks</h1>
                </div>
                <div>
                    <a class="btn btn-primary" href="/create-task">create new</a>
                </div>
            </div>

            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>name <a class="h5 pr-2" href='?<?= $pageQuery ?>sort=name+desc'>&#9660;</a><a class="h5 pr-2" href='?<?= $pageQuery ?>sort=name+asc'>&#9650;</a></th>
                        <th>email <a class="h5 pr-2" href='?<?= $pageQuery ?>sort=email+desc'>&#9660;</a><a class="h5 pr-2" href='?<?= $pageQuery ?>sort=email+asc'>&#9650;</a></th>
                        <th>description</th>
                        <th>status <a class="h5 pr-2" href='?<?= $pageQuery ?>sort=status+desc'>&#9660;</a><a class="h5 pr-2" href='?<?= $pageQuery ?>sort=status+asc'>&#9650;</a></th>
                        <th>edited by admin</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (!empty($tasks)) : ?>
                        <?php foreach($tasks as $task) : ?>
                        <tr>
                            <td><a href="/update-task?id=<?= $task['id'] ?>"><?= htmlspecialchars($task['name']) ?></a></td>
                            <td><?= htmlspecialchars($task['email']) ?></td>
                            <td><?= htmlspecialchars($task['description']) ?></td>
                            <td><?= Task::getStatusList()[$task['status']] ?? 'undefined' ?></td>
                            <td><?= $task['edited'] ? 'yes' : 'no' ?></td>
                        </tr>
                        <?php endforeach; ?>
                        <?php else : ?>
                            <tr><td colspan="4">No task so far</td></tr>
                    <?php endif ; ?>
                </tbody>
            </table>

            <?php if(isset($totalPages)): ?>
                <ul class="pagination">
                    <?php for ($i = 1; $i <= $totalPages; $i += 1): ?>
                    <li class="page-item"><a class="page-link <?= $activePage === $i ? 'bg-secondary' : ''?>" href="/?page=<?= $i, $sortQuery ?>"><?= $i ?></a></li>
                    <?php endfor; ?>
                </ul>
            <?php endif; ?>


        </main>
    </div>
</div>


</body>
</html>