<div class="d-flex justify-content-between my-3">
    <div>
        <h1 class="my-0">Update task</h1>
    </div>
</div>
<div class="row">
    <div class="col-12 col-lg-5">
        <form method="POST">
            <div class="form-group">
                <input type="text" name="task[name]" class="form-control" placeholder="Name" value="<?= $model->name ?>" readonly>
            </div>
            <div class="form-group">
                <input type="text" name="task[email]" class="form-control" placeholder="Email" value="<?= $model->email ?>" readonly>
            </div>
            <textarea class="form-control" name="task[description]" rows="3" placeholder="Task description"><?= $model->description ?></textarea>
            <div class="feedback text-danger">
                <?= $model->errors['description']['message'] ?? '' ?>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="task[status]" value="10" id="statusCheckbox" <?=  $model->getStatus() === 'completed' ? 'checked' : '' ?>>
                <label class="form-check-label" for="statusCheckbox">
                    Completed
                </label>
            </div>
            <button type="submit" class="btn btn-primary my-3">Submit</button>
        </form>
    </div>
</div>