<!DOCTYPE html>
<html lang="ru-RU">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $title ?? 'Task Manager'?></title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/dashboard.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Task Manager</a>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <?php if (\Core\App::$app['user']->isAdmin()): ?>
                <form method="post" class="m-0" action="/logout">
                    <button type="submit" class="btn btn-primary">
                    Log Out
                    </button>
                </form>
                <?php else: ?>
                    <a class="btn btn-primary" href="/login" data-method='post'>Log In</a>
                <?php endif; ?>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                </div>
            </nav>
        </div>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        <?php if (isset($_SESSION['flash'])) : ?>
            <div class="alert alert-<?= $_SESSION['flash']['class'] ?> my-3" role="alert">
                <strong><?= $_SESSION['flash']['message'] ?></strong>
                <?php unset( $_SESSION['flash'] );?>
            </div>
        <?php endif; ?>

            <?php include $viewFilePath; ?>

        </main>
    </div>
</body>
</html>